/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.annualForm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Annualform service. Represents a row in the &quot;annualform&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.annualForm.model.impl.AnnualformModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.annualForm.model.impl.AnnualformImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Annualform
 * @generated
 */
@ProviderType
public interface AnnualformModel extends BaseModel<Annualform> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a annualform model instance should use the {@link Annualform} interface instead.
	 */

	/**
	 * Returns the primary key of this annualform.
	 *
	 * @return the primary key of this annualform
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this annualform.
	 *
	 * @param primaryKey the primary key of this annualform
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the annualform ID of this annualform.
	 *
	 * @return the annualform ID of this annualform
	 */
	public long getAnnualformId();

	/**
	 * Sets the annualform ID of this annualform.
	 *
	 * @param annualformId the annualform ID of this annualform
	 */
	public void setAnnualformId(long annualformId);

	/**
	 * Returns the group ID of this annualform.
	 *
	 * @return the group ID of this annualform
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this annualform.
	 *
	 * @param groupId the group ID of this annualform
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this annualform.
	 *
	 * @return the user ID of this annualform
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this annualform.
	 *
	 * @param userId the user ID of this annualform
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this annualform.
	 *
	 * @return the user uuid of this annualform
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this annualform.
	 *
	 * @param userUuid the user uuid of this annualform
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the first name of this annualform.
	 *
	 * @return the first name of this annualform
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this annualform.
	 *
	 * @param firstName the first name of this annualform
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this annualform.
	 *
	 * @return the last name of this annualform
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this annualform.
	 *
	 * @param lastName the last name of this annualform
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the about of this annualform.
	 *
	 * @return the about of this annualform
	 */
	@AutoEscape
	public String getAbout();

	/**
	 * Sets the about of this annualform.
	 *
	 * @param about the about of this annualform
	 */
	public void setAbout(String about);

	/**
	 * Returns the gender of this annualform.
	 *
	 * @return the gender of this annualform
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this annualform.
	 *
	 * @param gender the gender of this annualform
	 */
	public void setGender(String gender);

	/**
	 * Returns the country of this annualform.
	 *
	 * @return the country of this annualform
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this annualform.
	 *
	 * @param country the country of this annualform
	 */
	public void setCountry(String country);

	@Override
	public Annualform cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}